[package]
name = "rust_to_c"
version = "0.1.0"
edition = "2018"

[lib]
name = "rust_to_c"
crate-type = ["cdylib", "staticlib"]

[dependencies]
blstrs = "0.7.1" 
ff = "0.13"
group = "0.13"
rand = "0.8"